home/bochelord/test_qubal/mysite/SEGURRRR/urls.py
# urls.py in mysite
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    #url(r'^courses/', include('qubalapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^django-session-idle-timeout/', include('django-session-idle-timeout.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'', include('social_auth.urls')),
    url(r'^', include('qubalapp.urls')),
)

urlpatterns += staticfiles_urlpatterns()

home/bochelord/test_qubal/mysite/qubalapp/urls.py
#urls.py in qubalapp

from django.conf.urls import patterns, url

from django.conf import settings

from qubalapp import views

urlpatterns = patterns('',
	
    # //this gets you to qubalapp/
    # url(r'^(?P<course_id>\d+)/$', views.courses, name='detail'),

    url(r'^course_listing/$', views.course_listing, name='course_listing'),

    # url(r'^static/main_engine/bootstrap.css', views.bootstrap, name='bootstrap'),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    url(r'^search-form/$', views.search_form, name='search-form'),
    url(r'^search/$', views.search),

    url(r'^profile/(?P<student_id>\d+)/$', views.profile),
    # url(r'^address/(?P<address_id>\d+)/$', views.address),

    url(r'^login/$', views.login),

    url(r'^teams/$', views.teams),

    url(r'^landing/$', views.landing),

    url(r'^logout/$', views.logout),

    url(r'^quest_listing/$', views.quest_listing, name='quest_listing'),

    url(r'^course/(?P<course_id>\d+)/$', views.course),

    url(r'^task/(?P<task_id>\d+)/$', views.task),

    # User starts a Quest
    url(r'^quest_started/$', views.quest_started),

    # //this gets you to index: qubal/
    url(r'^$', views.index, name='index'),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^register_character_landing/$', views.register_character_landing),

    url(r'^register_character/$', views.register_character),

    url(r'^qubal_character_init/$', views.qubal_character_init),

    url(r'^task_completed/$', views.task_completed),

    url(r'^enroll/$', views.enroll),

    url(r'^oracle_landing/$', views.oracle_landing),

    url(r'^oracle_process/$', views.oracle_process),

    url(r'^quiz_landing/$', views.quiz_landing),

    ## SPEX qubal views

    url(r'^spex_/$', views.spex_index),

    url(r'^spex_/spex_oracle_landing/$', views.spex_oracle_landing),

    url(r'^spex_oracle_process/$', views.spex_oracle_process),

    url(r'^spex_/courses/$', views.spex_course_listing),

    url(r'^spex_/teams/$', views.spex_teams),

    url(r'^spex_/quests/$', views.spex_quests),

    url(r'^spex_/profile/$', views.spex_profile),

    ## JAWA qubal views

    url(r'^jawa_/$', views.jawa_index),

    url(r'^jawa_/powers/$', views.jawa_powers),

    url(r'^jawa_/quests/$', views.jawa_quests),

    url(r'^jawa_/factions/$', views.jawa_factions),



    ## Social Auth views

    # url(r'^$', home, name='home'),
    # url(r'^done/$', done, name='done'),
    # url(r'^error/$', error, name='error'),
    # url(r'^logout/$', logout, name='logout'),
    # url(r'^form/$', form, name='form'),
    # url(r'^form2/$', form2, name='form2'),
    # #url(r'^admin/', include(admin.site.urls)),
    # #url(r'^facebook/', facebook_view, name='fb_app'),
    # #url(r'^ok/$', ok_app, name='ok_app'),
    # #url(r'^ok/info/$', ok_app_info, name='ok_app_info'),
    # url(r'^close_login_popup/$', close_login_popup, name='login_popup_close'),
    
)

home/bochelord/test_qubal/mysite/urls.py
# urls.py in mysite
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    #url(r'^courses/', include('qubalapp.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^django-session-idle-timeout/', include('django-session-idle-timeout.urls')),
    # url(r'^test/dajaxice/', include('dajaxice.urls')),
    
    url(r'', include('social_auth.urls')),
    url(r'^', include('qubalapp.urls')),
)

urlpatterns += staticfiles_urlpatterns()

home/bochelord/test_qubal/mysite/qubalapp/models.py
import datetime, logging
from django.utils import timezone
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from model_utils.managers import InheritanceManager

# Create your models here.

class Nickname(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()

    def __unicode__(self):
        return str(self.id)+": "+self.title


class Achievement(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    # points = models.IntegerField(default=0)
    image = models.ImageField(upload_to="images/achievements",default="default_images/default_achievement.jpg")
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(50, 50)],
                                      format='JPEG',
                                      options={'quality': 100})
    unlock_nickname = models.OneToOneField('Nickname', primary_key=False, blank=True, null=True)
    unlocked_date = models.DateTimeField('Unlocked Date', blank=True, null=True)
    is_key = models.BooleanField(default=False)
    # de momento no sabemos que desbloquea la key.

    def __unicode__(self):
        return str(self.id)+": "+self.name


class Power(models.Model):
    # quubs earned can be calculated
    teamwork = models.IntegerField(default=0)
    teamwork_quubs = models.IntegerField(default=0)
    communication = models.IntegerField(default=0)
    communication_quubs = models.IntegerField(default=0)
    responsability = models.IntegerField(default=0)
    responsability_quubs = models.IntegerField(default=0)
    perseverance = models.IntegerField(default=0)
    perseverance_quubs = models.IntegerField(default=0)
    mastery = models.IntegerField(default=0)
    mastery_quubs = models.IntegerField(default=0)
    focus = models.IntegerField(default=0)
    focus_quubs = models.IntegerField(default=0)


    def __unicode__(self):
        return str(self.id)+": Mas "+str(self.mastery)+" Foc "+str(self.focus)+" Tem "+str(self.teamwork)+" Com "+str(self.communication)+" Res "+str(self.responsability)+" Per "+str(self.perseverance)


# class Students_in_Course(models.Model):
#     student = models.ForeignKey('Student')
#     course = models.ForeignKey('Course')


# Course that helds several students
class Course(models.Model):
    image = models.ImageField(upload_to="images/courses",default="default_images/default_course_dark.jpg")
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(50, 50)],
                                      format='JPEG',
                                      options={'quality': 100})
    name = models.CharField(max_length=100)
    description = models.TextField()
    starting_date = models.DateTimeField('Course Starting Date')
    ending_date = models.DateTimeField('Course Ending Date')
    has_students = models.ManyToManyField('Student', blank=True, null=True) # , through=Students_in_Course
    has_quests = models.ManyToManyField('Quest')
    has_teams = models.ManyToManyField('Team', blank=True, null=True)
    has_achievements = models.ManyToManyField('Achievement')
    has_documents = models.ManyToManyField('Educational_Document', blank=True, null=True) #through educational_documents_in_course? hay que probar el manytomany sin el through
    has_rewards = models.ManyToManyField('Reward')
    what_should_i_know_list = models.ManyToManyField('Course', blank=True, null=True)
    what_should_i_know_description = models.TextField()
    what_should_i_learn_list = models.ManyToManyField('Course', blank=True, null=True, related_name='what_should_i_learn_courses_list')
    what_should_i_learn_description = models.TextField()

    author = models.ForeignKey('Teacher')

    is_live = models.BooleanField(default=False)

    def __unicode__(self):

        if self.is_live:
            live_text = 'live!'
        else:
            live_text = 'not live :('

        return self.name + ' Author: ' + self.author.user.username + ' and is ' + live_text

    def long_course(self):
        duration = self.ending_date - self.starting_date 
        if duration < datetime.timedelta(days=3):
            islong = False
        else:
            islong = True

        return islong
        
            
        long_course.admin_order_field = 'date'
        long_course.boolean = True
        long_course.short_description = 'Course Duration'



class Team(models.Model):
    
    HAPPINESS = (
        ('normal', 'Normal'),
        ('unhappy', 'Unhappy'),
        ('happy', 'Happy'),
    )

    name = models.CharField(max_length=100)
    is_in_course = models.ForeignKey('Course')
    description = models.TextField()
    image = models.ImageField(upload_to="images/teams",default="default_images/default_team_avatar.jpg")
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(50, 50)],
                                      format='JPEG',
                                      options={'quality': 100})
    has_students = models.ManyToManyField('Student')
    has_teachers = models.ManyToManyField('Teacher')
    captain = models.ForeignKey('Student', related_name='Team_Captain')
#    has_challenges = models.ManyToManyField('Challenge', blank=True, null=True)
    happiness = models.CharField(max_length=7, choices=HAPPINESS)
    has_documents = models.ForeignKey('Educational_Document', blank=True, null=True)

    def __unicode__(self):
        return self.name
    
# Student that have been enrolled in a course :D
class Person(models.Model):
    
    GENDER = (
        ('m', 'male'),
        ('f', 'female')
        )

    # role = Student, Teacher
    user = models.OneToOneField(User, primary_key=True)
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    birth = models.DateTimeField('Birthdate')
    email = models.EmailField(max_length=75)
    phone_number = models.CharField(max_length=13)
    image = models.ImageField(upload_to="images/persons",default="default_images/default_avatar_grey.jpg")
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(50, 50)],
                                      format='JPEG',
                                      options={'quality': 100})
    xp  = models.IntegerField(default=0)
    #level = models.IntegerField(default=1)

    has_nicknames = models.ManyToManyField('Nickname', blank=True, null=True)
    has_achievements = models.ManyToManyField('Achievement', blank=True, null=True)

    twitter = models.CharField(max_length=250, blank=True, null=True)
    facebook = models.CharField(max_length=250, blank=True, null=True)
    dropbox = models.CharField(max_length=250, blank=True, null=True)

    has_address = models.ForeignKey('Address', blank=True, null=True)
    has_powers = models.OneToOneField('Power', blank=True, null=True)
    # has_edu_skills = models.ManyToManyField('Edu_Skill')
    # has_personal_skills = models.ManyToManyField('Personal_Skill')
    has_documents = models.ForeignKey('Educational_Document', blank=True, null=True)
    is_in_school = models.ForeignKey('School', blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER)
    personal_quote = models.CharField(max_length=125)

    objects = InheritanceManager()

    def __unicode__(self):
        return self.name+" "+self.lastname

    
class Courses_Completed_By_Student(models.Model):
    student = models.ForeignKey('Student')
    course = models.ForeignKey('Course')


class Student(Person):

    CHARACTER_CLASS = (
        ('no_class', 'No Class!'),
        ('explorer', 'Explorer'),
        ('activist', 'Activist'),
        ('unifier', 'Unifier'),
        ('inventor', 'Inventor'),
        )

    is_team_member_of = models.ManyToManyField('Team', blank=True, null=True)
    #is_captain_of = models.ForeignKey('Team', blank=True, null=True, related_name='Student_Captain_of_Team')
    courses_completed = models.ManyToManyField('Course', related_name='Courses_Completed_By_Student', blank=True, null=True)
    quests_completed = models.ManyToManyField('Quest', related_name='Quests_Completed_By_Student', blank=True, null=True)
    challenged_completed = models.ManyToManyField('Challenge', related_name='Challenges_Completed_By_Student', blank=True, null=True)
    tasks_completed = models.ManyToManyField('Task', related_name='Tasks_Completed_By_Student', blank=True, null=True)
    active_courses = models.ManyToManyField('Course', blank=True, null=True)
    active_quests = models.ManyToManyField('Quest', blank=True, null=True)
    active_challenges = models.ManyToManyField('Challenge', blank=True, null=True)
    active_tasks = models.ManyToManyField('Task', blank=True, null=True)
    character_class = models.CharField(max_length=12, choices=CHARACTER_CLASS)
    # Add abilities for February.

class Teacher(Person):
    
    is_tutor_of_teams = models.ManyToManyField('Team', blank=True, null=True)
    teach_in_courses = models.ManyToManyField('Course', blank=True, null=True)
    background_cv = models.TextField()




# School
class School(models.Model):
    name = models.CharField(max_length=250)
    has_address = models.OneToOneField('Address')
    has_students = models.ManyToManyField('Student')
    has_teachers = models.ManyToManyField('Teacher')

    def __unicode__(self):
        return self.name


# Address
class Address(models.Model):
    street = models.CharField(max_length=100)
    number = models.IntegerField(default=0)
    floor = models.IntegerField(default=0)
    door = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    postcode = models.CharField(max_length=10)
    country = models.CharField(max_length=30)
    

home/bochelord/test_qubal/mysite/qubalapp/templates/qubalapp/course_listing_teacher.html
<!DOCTYPE HTML>
<html lang="en">

<head>
	<title>Qubal | Courses Teacher</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/bootstrap-flatly.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/font-awesome.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/navbar.css">
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/course_listing.css">
</head>

<body>

{% autoescape off %}{{ navbar_content }}{% endautoescape %}

<div class="container">
<span class="your-courses-title"> Courses authored by you</span><br><br><br>
<div class='row'>
    {% load imagekit %}
    
      {% if authored_course_list %}
        
          {% for course in authored_course_list.all %}

              {% if course.image %}
                  {% generateimage 'qubalapp:thumbnail100x100' source=course.image as imagen %}
                    <div class='course-box'>
                    <div class='well'>
                    <img class="img-format img-circle pull-left" src='{{ imagen.url }}' />
              {% else %}
                    <div class='course-box'>
                    <div class='well'>
                    <img class="img-format img-circle pull-left" src='{{ STATIC_URL }}default_images/default_course_dark.jpg' width='100' />
              {% endif %}

              {% if course.is_live %}
                <span class="label label-success pull-right">live</span>
              {% else %}
                <span class="label label-important pull-right">NOT LIVE!</span>
              {% endif %}
              
                <div class="course-box-title">
                  <a href="{{ SUNRISE_URL }}courses/{{ course.id }}/">{{ course.name }}</a>
                </div>

                <div class="course-box-date">
                  <span class>{{ course.starting_date|date:"d M Y" }}</span>
                </div>

                <div class="course-box-description">
                  {% if course.description|length > 125 %}
                    <span>{{ course.description|truncatechars:125 }}</span>
                  {% else %} 
                    <span>{{ course.description }}</span>
                  {% endif %}
                </div>

              </div>
            </div>

          {% endfor %}
      {% else %}
              <p class="your-courses">You have not created any Course yet! Check some courses here below!</p>
      {% endif %}
<div class="clearfix"></div>
<hr class="central-hr"><br>
<span class="all-courses-title"> Other Courses </span><br><br><br>
      {% for course in not_authored_course_list.all %}
              {% if course.image %}
                  {% generateimage 'qubalapp:thumbnail100x100' source=course.image as imagen %}
                    <div class='course-box'>
                    <div class='well'>
                    <img class="img-format img-circle pull-left" src='{{ imagen.url }}' />
              {% else %}
                    <div class='course-box'>
                    <div class='well'>
                    <img class="img-format img-circle pull-left" src='{{ STATIC_URL }}default_images/default_course_dark.jpg' width='100'/>
              {% endif %}

              {% if course.is_live %}
                <span class="label label-success pull-right">live</span>
              {% else %}
                <span class="label label-important pull-right">NOT LIVE!</span>
              {% endif %}
              
              
                <div class="course-box-title">
                  <a href="{{ SUNRISE_URL }}courses/{{ course.id }}/">{{ course.name }}</a>
                </div>

                <div class="course-box-date">
                  <span class>{{ course.starting_date|date:"d M Y" }}</span>
                </div>

                <div class="course-box-description">
                  {% if course.description|length > 125 %}
                    <span>{{ course.description|truncatechars:125 }}</span>
                  {% else %}
                    <span>{{ course.description }}</span>
                  {% endif %}
                </div>

              </div>
            </div>
      {% endfor %}
</div>
<hr class="mini-hr">


</div>

<script src="{{ STATIC_URL }}qubalapp/main_engine/js/jquery.js"></script>
<script src="{{ STATIC_URL }}qubalapp/main_engine/js/bootstrap.js"></script>



</body>
</html>

home/bochelord/test_qubal/mysite/qubalapp/templates/qubalapp/deliverable_field.html
{% load crispy_forms_field %}

<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors%}{% if field.errors %} error{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">

    {% if field.label %}
        <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    
<div class='row'>
    <div class="span2 well">
        <div class="fileupload fileupload-new " data-provides="fileupload">
          <div>
            <span class="fileupload-new">
              <span class="btn btn-info btn-file"><i class='icon-upload'></i> Upload file:  <input type="file" name="{{ field.html_name }}" id="id_{{ field.html_name }}" value="{{ field.value }}" />
              </span>
            </span>
            <a href="#" class="btn btn-warning fileupload-exists" data-dismiss="fileupload"><i class='icon-repeat'></i> Change file?</a>
          </div>
          <i class='icon-file'></i>&nbsp;<div class="fileupload-preview fileupload-exists"></div>
        </div>
    </div>
</div>

</div>

home/bochelord/test_qubal/mysite/qubalapp/templates/qubalapp/file_field.html
{% load crispy_forms_field %}

<div id="div_{{ field.auto_id }}" class="control-group{% if form_show_errors%}{% if field.errors %} error{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
    {% if field.label %}
        <label for="{{ field.id_for_label }}" class="control-label {% if field.field.required %}requiredField{% endif %}">
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}

    
<div class='row'>
    <div class="span5">
        <div class="fileupload fileupload-new " data-provides="fileupload">
          <div class="fileupload-new thumbnail" style="width: 150px; height: 150px;"><img src="http://www.placehold.it/150x150/EFEFEF/AAAAAA" /></div>
          <div class="fileupload-preview fileupload-exists thumbnail" style="width: 150px; height: 150px;"></div>&nbsp;

          <div>
            <span class="fileupload-new">
              <span class="btn btn-info btn-file"><i class='icon-upload'></i> Upload image: <!-- <span class="fileupload-exists">Change</span> --><input type="file" name="{{ field.html_name }}" id="id_{{ field.html_name }}" value="{{ field.value }}" /></span></span>
            </span>
         
            <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class='icon-remove'></i> Remove and change</a>
          </div>

          
        </div>
    </div>



</div>



</div>

home/bochelord/test_qubal/mysite/qubalapp/templates/qubalapp/profile.html
<!DOCTYPE HTML>
<html lang="en">

<head>
	<title>Qubal | Courses</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/bootstrap-flatly.css"/>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/font-awesome.css"/>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/navbar.css">
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}qubalapp/main_engine/css/profile.css"/>
</head>

<body>

{% autoescape off %}{{ navbar_content }}{% endautoescape %}

<div class="container">
{% load imagekit %}
{% load humanize %}

<div class='row'>
	<!-- <div class='span12'>


		<h4>Profile</h4>
		<hr><br>
		<div class='text_name_title'>
			{{ student.name|upper }} {{ student.lastname}}
		</div>

		
			<hr>

			<div class='row'>
				<div class='span3'>
					<p>STATUS: <span class='label label-mini label-warning'>placeholder</span>
					</p>
				</div>
				<div class='span1'>
					FOO
				</div>

			</div>


			<h4>Cursos</h4>
	    <ul>
			{% for n in courses_list %}
				<li><a href='/courses/{{n.user_id}}/'>{{n.name}}</a></li>
			{% endfor %}
	    </ul>
			<a class="btn" href="/">Home</a>

		

		<div class='span1'>
			PORK
		</div>

	</div> -->

	<div class='span4'> <!-- sidebar on the left -->
		<div class='text-name'>
					{{ student.name }} {{ student.lastname }}
		</div>
		<div class='well'>
			<div class='level-box pull-right'>
				
				<div class='pull-right label label-inverse profile_level'>
					<div class='opensans-bold offset-cuarto'>
						<span class='totalxp_text pull-right'>{{ total_xp }}</span> 
						<div class='totalxp_text'>XP</div>
						<br><br>
						<span class='level-label'>level</span>
						<span class='pagination-centered current_level_text'>{{ current_level }}&nbsp;</span>
					</div>
					<br>
					<p class='class-text pagination-centered '>{{ student.get_character_class_display|upper }}</p>
				</div>
				<div class='clearfix'>
				</div>
				<div class=''>
					<span class='pull-right'>  {{ current_xp }}/{{ xp_needed_for_level_up }} XP <i class='icon-level-up letter-large' title='levelup to {{ next_level }} at: {{next_level_at}} XP'></i></span>
                	<div class="span1ymedio progress progress-striped active pull-right">
                  		<div class="bar bar-warning" style="width:{{ percent_current_xp }}%;" title='level {{ current_level}} to {{ next_level }} progress: {{ current_xp }}/{{ xp_needed_for_level_up }}xp - {{ percent_current_xp }}%'></div>
                  	</div>
                </div>
                

			</div>

			<!-- <div class='sidebar_profile'> -->
				
				<div class='profile-image'>
					{% if student.image %}

			          {% generateimage 'qubalapp:thumbnail150x150' source=student.image as tn2 %}
			          <img src='{{ tn2.url }}' class='img-circle' title='{{ student.name}} {{ student.lastname }} - level {{ current_level }} - {{ student.get_character_class_display }}' rel="tooltip-left"/>
			        {% else %}
			          <img src='{{ STATIC_URL }}default_images/default_avatar_grey.jpg' width='150' class='img-circle' title='{{ student.name}} {{ student.lastname }} - level {{ current_level }} - {{ student.get_character_class_display }}' rel="tooltip-left"/>
			        {% endif %}
				</div>
			<!-- </div> -->

			<br>
			<div class='row'>
				<div class=''>
					<i class='icon-map-marker iconbig'></i>
				</div>
				<div class='span3'>
					<p class='opensans-bold gray-text'>{{ student.birth|timesince }} old {{ student.get_gender_display }} from {{ student.has_address.city}}, {{ student.has_address.country}}</p>
				</div>
			</div>
			<div class='row'>
				<div class=''>
					<i class='icon-book iconbig'></i>
				</div>
				<div class='span3'>
					<p class='info-widget-text'>Studying {{ courses_list.0.name }} at {{ student.is_in_school.name }} in {{ student.is_in_school.has_address.city }}, {{ student.is_in_school.has_address.country}}</p>
				</div>
			</div>
			<div class='row'>
				<div class=''>
					<i class='icon-comment iconbig'></i>
				</div>
				<div class='span3'>
					<p class='info-widget-text'>"{{student.personal_quote}}"</p>
				</div>
			</div>
			<div class='row'>
				<div class='span3 pagination-centered'>
					<strong>Find me here</strong>
				</div>
			</div>
			<div class='row'>
				<div class='span3 pagination-centered'>
					<i class='icon-facebook-sign iconbig'></i> <i class='icon-twitter-sign iconbig'></i> <i class='icon-linkedin-sign iconbig'></i>
				</div>
			</div>
<!-- 			<div class="media-box">
				<i class='icon-map-marker iconbig'></i>
				<strong>This is a title</strong> 
				<p>this is some text, lalalala </p>
			</div> -->


		</div>
	</div> <!-- sidebar on the left END -->


	<div class='span8'> <!-- main container on the right -->
		<div class='well'>
			PLACEHOLDER
		</div>
	</div>

</div>

</div>



</body>
</html>